// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activities.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addEvidence = `-- name: AddEvidence :one
INSERT INTO activity_evidences (activity_id, evidence_url, description)
VALUES ($1, $2, $3)
RETURNING id, activity_id, evidence_url, description, created_at
`

type AddEvidenceParams struct {
	ActivityID  uuid.UUID   `json:"activity_id"`
	EvidenceUrl string      `json:"evidence_url"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) AddEvidence(ctx context.Context, arg AddEvidenceParams) (ActivityEvidence, error) {
	row := q.db.QueryRow(ctx, addEvidence, arg.ActivityID, arg.EvidenceUrl, arg.Description)
	var i ActivityEvidence
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.EvidenceUrl,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities (
    user_id, 
    ladder_id, 
    title, 
    description, 
    progress_percentage, 
    impact_summary, 
    is_pdi_target
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, ladder_id, title, description, is_pdi_target, progress_percentage, impact_summary, completed_at, created_at, updated_at
`

type CreateActivityParams struct {
	UserID             uuid.UUID   `json:"user_id"`
	LadderID           uuid.UUID   `json:"ladder_id"`
	Title              string      `json:"title"`
	Description        pgtype.Text `json:"description"`
	ProgressPercentage int32       `json:"progress_percentage"`
	ImpactSummary      pgtype.Text `json:"impact_summary"`
	IsPdiTarget        bool        `json:"is_pdi_target"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.UserID,
		arg.LadderID,
		arg.Title,
		arg.Description,
		arg.ProgressPercentage,
		arg.ImpactSummary,
		arg.IsPdiTarget,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LadderID,
		&i.Title,
		&i.Description,
		&i.IsPdiTarget,
		&i.ProgressPercentage,
		&i.ImpactSummary,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteActivity = `-- name: DeleteActivity :exec
DELETE FROM activities 
WHERE id = $1 AND user_id = $2
`

type DeleteActivityParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteActivity(ctx context.Context, arg DeleteActivityParams) error {
	_, err := q.db.Exec(ctx, deleteActivity, arg.ID, arg.UserID)
	return err
}

const findActivityByID = `-- name: FindActivityByID :one
SELECT
	a.id,
	a.title,
	a.description,
	a.impact_summary,
	a.is_pdi_target,
	a.progress_percentage,
	a.ladder_id,
	a.user_id 
FROM activities a 
WHERE a.id = $1
`

type FindActivityByIDRow struct {
	ID                 uuid.UUID   `json:"id"`
	Title              string      `json:"title"`
	Description        pgtype.Text `json:"description"`
	ImpactSummary      pgtype.Text `json:"impact_summary"`
	IsPdiTarget        bool        `json:"is_pdi_target"`
	ProgressPercentage int32       `json:"progress_percentage"`
	LadderID           uuid.UUID   `json:"ladder_id"`
	UserID             uuid.UUID   `json:"user_id"`
}

func (q *Queries) FindActivityByID(ctx context.Context, id uuid.UUID) (FindActivityByIDRow, error) {
	row := q.db.QueryRow(ctx, findActivityByID, id)
	var i FindActivityByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ImpactSummary,
		&i.IsPdiTarget,
		&i.ProgressPercentage,
		&i.LadderID,
		&i.UserID,
	)
	return i, err
}

const findActivityComposition = `-- name: FindActivityComposition :many
SELECT 
    cl.level,
    COUNT(a.id)::int as total_activities,
    SUM(cl.xp_reward)::int as total_xp
FROM activities a
JOIN career_ladder cl ON a.ladder_id = cl.id
WHERE a.user_id = $1 AND a.progress_percentage = 100
GROUP BY cl.level
ORDER BY cl.level ASC
`

type FindActivityCompositionRow struct {
	Level           LadderLevel `json:"level"`
	TotalActivities int32       `json:"total_activities"`
	TotalXp         int32       `json:"total_xp"`
}

func (q *Queries) FindActivityComposition(ctx context.Context, userID uuid.UUID) ([]FindActivityCompositionRow, error) {
	rows, err := q.db.Query(ctx, findActivityComposition, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindActivityCompositionRow
	for rows.Next() {
		var i FindActivityCompositionRow
		if err := rows.Scan(&i.Level, &i.TotalActivities, &i.TotalXp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findActivityDetail = `-- name: FindActivityDetail :one
SELECT 
    a.id, a.title, a.progress_percentage, a.impact_summary,
    cl.level
FROM activities a
JOIN career_ladder cl ON a.ladder_id = cl.id
WHERE a.id = $1
`

type FindActivityDetailRow struct {
	ID                 uuid.UUID   `json:"id"`
	Title              string      `json:"title"`
	ProgressPercentage int32       `json:"progress_percentage"`
	ImpactSummary      pgtype.Text `json:"impact_summary"`
	Level              LadderLevel `json:"level"`
}

func (q *Queries) FindActivityDetail(ctx context.Context, id uuid.UUID) (FindActivityDetailRow, error) {
	row := q.db.QueryRow(ctx, findActivityDetail, id)
	var i FindActivityDetailRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ProgressPercentage,
		&i.ImpactSummary,
		&i.Level,
	)
	return i, err
}

const findActivityWithLadder = `-- name: FindActivityWithLadder :one
SELECT 
    a.id, 
    a.user_id, 
    a.ladder_id, 
    a.title, 
    a.description, 
    a.progress_percentage, 
    a.impact_summary, 
    a.completed_at, 
    a.created_at,
    cl.level, 
    cl.xp_reward, 
    cl.technical,
    cl.expected_results,
    cl.leadership_scope
FROM activities a
JOIN career_ladder cl ON a.ladder_id = cl.id
WHERE a.id = $1
`

type FindActivityWithLadderRow struct {
	ID                 uuid.UUID   `json:"id"`
	UserID             uuid.UUID   `json:"user_id"`
	LadderID           uuid.UUID   `json:"ladder_id"`
	Title              string      `json:"title"`
	Description        pgtype.Text `json:"description"`
	ProgressPercentage int32       `json:"progress_percentage"`
	ImpactSummary      pgtype.Text `json:"impact_summary"`
	CompletedAt        pgtype.Date `json:"completed_at"`
	CreatedAt          pgtype.Date `json:"created_at"`
	Level              LadderLevel `json:"level"`
	XpReward           int32       `json:"xp_reward"`
	Technical          string      `json:"technical"`
	ExpectedResults    string      `json:"expected_results"`
	LeadershipScope    string      `json:"leadership_scope"`
}

func (q *Queries) FindActivityWithLadder(ctx context.Context, id uuid.UUID) (FindActivityWithLadderRow, error) {
	row := q.db.QueryRow(ctx, findActivityWithLadder, id)
	var i FindActivityWithLadderRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LadderID,
		&i.Title,
		&i.Description,
		&i.ProgressPercentage,
		&i.ImpactSummary,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.Level,
		&i.XpReward,
		&i.Technical,
		&i.ExpectedResults,
		&i.LeadershipScope,
	)
	return i, err
}

const findCurrentTargetLevel = `-- name: FindCurrentTargetLevel :one
SELECT 
    cl.level,
    cl.id as ladder_id
FROM xp_target xt
JOIN career_ladder cl ON xt.ladder_id = cl.id
WHERE xt.year = $1
LIMIT 1
`

type FindCurrentTargetLevelRow struct {
	Level    LadderLevel `json:"level"`
	LadderID uuid.UUID   `json:"ladder_id"`
}

func (q *Queries) FindCurrentTargetLevel(ctx context.Context, year int32) (FindCurrentTargetLevelRow, error) {
	row := q.db.QueryRow(ctx, findCurrentTargetLevel, year)
	var i FindCurrentTargetLevelRow
	err := row.Scan(&i.Level, &i.LadderID)
	return i, err
}

const findDetailedActivityReport = `-- name: FindDetailedActivityReport :many
SELECT 
    a.id,
    a.title,
    a.progress_percentage,
    a.is_pdi_target,
    cl.level,
    cl.xp_reward,
    (
        SELECT array_agg(ap.pillar::text)
        FROM activity_pillars ap
        WHERE ap.activity_id = a.id
    ) as pillars,
    COALESCE(
        (
            SELECT json_agg(json_build_object(
                'url', ae.evidence_url,
                'description', ae.description,
                'created_at', ae.created_at
            ))
            FROM activity_evidences ae
            WHERE ae.activity_id = a.id
        ), 
        '[]'
    )::json as evidences
FROM activities a
JOIN career_ladder cl ON a.ladder_id = cl.id
WHERE a.user_id = $1
ORDER BY a.progress_percentage DESC, a.created_at DESC
`

type FindDetailedActivityReportRow struct {
	ID                 uuid.UUID   `json:"id"`
	Title              string      `json:"title"`
	ProgressPercentage int32       `json:"progress_percentage"`
	IsPdiTarget        bool        `json:"is_pdi_target"`
	Level              LadderLevel `json:"level"`
	XpReward           int32       `json:"xp_reward"`
	Pillars            interface{} `json:"pillars"`
	Evidences          []byte      `json:"evidences"`
}

func (q *Queries) FindDetailedActivityReport(ctx context.Context, userID uuid.UUID) ([]FindDetailedActivityReportRow, error) {
	rows, err := q.db.Query(ctx, findDetailedActivityReport, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindDetailedActivityReportRow
	for rows.Next() {
		var i FindDetailedActivityReportRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ProgressPercentage,
			&i.IsPdiTarget,
			&i.Level,
			&i.XpReward,
			&i.Pillars,
			&i.Evidences,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEvidencesByActivity = `-- name: FindEvidencesByActivity :many
SELECT id, activity_id, evidence_url, description, created_at FROM activity_evidences 
WHERE activity_id = $1 
ORDER BY created_at DESC
`

func (q *Queries) FindEvidencesByActivity(ctx context.Context, activityID uuid.UUID) ([]ActivityEvidence, error) {
	rows, err := q.db.Query(ctx, findEvidencesByActivity, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityEvidence
	for rows.Next() {
		var i ActivityEvidence
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.EvidenceUrl,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findGapAnalysis = `-- name: FindGapAnalysis :many
SELECT 
    cl.level,
    ap.pillar::text as pillar,
    xt.target as target_xp,
    SUM(CASE WHEN a.progress_percentage = 100 THEN cl.xp_reward ELSE 0 END)::int as achieved_xp,
    (xt.target - SUM(CASE WHEN a.progress_percentage = 100 THEN cl.xp_reward ELSE 0 END))::int as gap_xp,
    ROUND(
        (SUM(CASE WHEN a.progress_percentage = 100 THEN cl.xp_reward ELSE 0 END)::float / xt.target::float) * 100
    )::int as completion_percentage
FROM xp_target xt
JOIN career_ladder cl ON xt.ladder_id = cl.id
LEFT JOIN activities a ON a.ladder_id = cl.id AND a.user_id = $1
LEFT JOIN activity_pillars ap ON a.id = ap.activity_id
WHERE xt.year = $2 -- Analisamos o gap para o ano corrente
GROUP BY cl.level, ap.pillar, xt.target
ORDER BY cl.level, ap.pillar
`

type FindGapAnalysisParams struct {
	UserID uuid.UUID `json:"user_id"`
	Year   int32     `json:"year"`
}

type FindGapAnalysisRow struct {
	Level                LadderLevel `json:"level"`
	Pillar               string      `json:"pillar"`
	TargetXp             int32       `json:"target_xp"`
	AchievedXp           int32       `json:"achieved_xp"`
	GapXp                int32       `json:"gap_xp"`
	CompletionPercentage int32       `json:"completion_percentage"`
}

func (q *Queries) FindGapAnalysis(ctx context.Context, arg FindGapAnalysisParams) ([]FindGapAnalysisRow, error) {
	rows, err := q.db.Query(ctx, findGapAnalysis, arg.UserID, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindGapAnalysisRow
	for rows.Next() {
		var i FindGapAnalysisRow
		if err := rows.Scan(
			&i.Level,
			&i.Pillar,
			&i.TargetXp,
			&i.AchievedXp,
			&i.GapXp,
			&i.CompletionPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPdiDashboard = `-- name: FindPdiDashboard :many
SELECT 
    cl.level,
    ap.pillar::text as pillar,
    -- Soma tudo o que foi planejado no PDI (independente de estar pronto)
    SUM(CASE WHEN a.is_pdi_target = true THEN cl.xp_reward ELSE 0 END)::int as total_pdi_planned,
    -- Soma apenas o que foi de fato concluído
    SUM(CASE WHEN a.progress_percentage = 100 THEN cl.xp_reward ELSE 0 END)::int as total_achieved,
    -- XP extra: o que foi concluído mas NÃO estava no PDI original
    SUM(CASE WHEN a.progress_percentage = 100 AND a.is_pdi_target = false THEN cl.xp_reward ELSE 0 END)::int as overdelivery_xp,
    COUNT(a.id)::int as activity_count
FROM activities a
JOIN activity_pillars ap ON a.id = ap.activity_id
JOIN career_ladder cl ON a.ladder_id = cl.id
WHERE a.user_id = $1
GROUP BY cl.level, ap.pillar
ORDER BY cl.level ASC
`

type FindPdiDashboardRow struct {
	Level           LadderLevel `json:"level"`
	Pillar          string      `json:"pillar"`
	TotalPdiPlanned int32       `json:"total_pdi_planned"`
	TotalAchieved   int32       `json:"total_achieved"`
	OverdeliveryXp  int32       `json:"overdelivery_xp"`
	ActivityCount   int32       `json:"activity_count"`
}

func (q *Queries) FindPdiDashboard(ctx context.Context, userID uuid.UUID) ([]FindPdiDashboardRow, error) {
	rows, err := q.db.Query(ctx, findPdiDashboard, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindPdiDashboardRow
	for rows.Next() {
		var i FindPdiDashboardRow
		if err := rows.Scan(
			&i.Level,
			&i.Pillar,
			&i.TotalPdiPlanned,
			&i.TotalAchieved,
			&i.OverdeliveryXp,
			&i.ActivityCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserActivities = `-- name: FindUserActivities :many
SELECT 
    a.id,
    a.title,
    a.progress_percentage,
    a.is_pdi_target,
    cl.level,
    COALESCE(string_agg(ap.pillar::text, ', '), '') as pillars
FROM activities a
JOIN career_ladder cl ON a.ladder_id = cl.id
LEFT JOIN activity_pillars ap ON a.id = ap.activity_id
WHERE a.user_id = $1
GROUP BY a.id, cl.level
ORDER BY a.created_at DESC
`

type FindUserActivitiesRow struct {
	ID                 uuid.UUID   `json:"id"`
	Title              string      `json:"title"`
	ProgressPercentage int32       `json:"progress_percentage"`
	IsPdiTarget        bool        `json:"is_pdi_target"`
	Level              LadderLevel `json:"level"`
	Pillars            interface{} `json:"pillars"`
}

func (q *Queries) FindUserActivities(ctx context.Context, userID uuid.UUID) ([]FindUserActivitiesRow, error) {
	rows, err := q.db.Query(ctx, findUserActivities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindUserActivitiesRow
	for rows.Next() {
		var i FindUserActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ProgressPercentage,
			&i.IsPdiTarget,
			&i.Level,
			&i.Pillars,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserActivities = `-- name: ListUserActivities :many
SELECT 
    id, 
    user_id, 
    ladder_id, 
    title, 
    description, 
    progress_percentage, 
    impact_summary, 
    completed_at, 
    created_at
FROM activities 
WHERE user_id = $1 
ORDER BY created_at DESC
`

type ListUserActivitiesRow struct {
	ID                 uuid.UUID   `json:"id"`
	UserID             uuid.UUID   `json:"user_id"`
	LadderID           uuid.UUID   `json:"ladder_id"`
	Title              string      `json:"title"`
	Description        pgtype.Text `json:"description"`
	ProgressPercentage int32       `json:"progress_percentage"`
	ImpactSummary      pgtype.Text `json:"impact_summary"`
	CompletedAt        pgtype.Date `json:"completed_at"`
	CreatedAt          pgtype.Date `json:"created_at"`
}

func (q *Queries) ListUserActivities(ctx context.Context, userID uuid.UUID) ([]ListUserActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listUserActivities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserActivitiesRow
	for rows.Next() {
		var i ListUserActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LadderID,
			&i.Title,
			&i.Description,
			&i.ProgressPercentage,
			&i.ImpactSummary,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserActivitiesWithEvidences = `-- name: ListUserActivitiesWithEvidences :many
SELECT 
    a.id,
    a.title,
    a.progress_percentage,
    cl.level,
    COALESCE(
        (SELECT json_agg(ed) FROM (
            SELECT id, evidence_url, description FROM activity_evidences WHERE activity_id = a.id
        ) ed), 
        '[]'
    )::json as evidences
FROM activities a
JOIN career_ladder cl ON a.ladder_id = cl.id
WHERE a.user_id = $1
GROUP BY a.id, cl.level
ORDER BY a.created_at DESC
`

type ListUserActivitiesWithEvidencesRow struct {
	ID                 uuid.UUID   `json:"id"`
	Title              string      `json:"title"`
	ProgressPercentage int32       `json:"progress_percentage"`
	Level              LadderLevel `json:"level"`
	Evidences          []byte      `json:"evidences"`
}

func (q *Queries) ListUserActivitiesWithEvidences(ctx context.Context, userID uuid.UUID) ([]ListUserActivitiesWithEvidencesRow, error) {
	rows, err := q.db.Query(ctx, listUserActivitiesWithEvidences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserActivitiesWithEvidencesRow
	for rows.Next() {
		var i ListUserActivitiesWithEvidencesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ProgressPercentage,
			&i.Level,
			&i.Evidences,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActivityProgress = `-- name: UpdateActivityProgress :one
UPDATE activities 
SET 
    progress_percentage = $2,
    updated_at = NOW()
WHERE id = $1 AND user_id = $3
RETURNING id, user_id, ladder_id, title, description, is_pdi_target, progress_percentage, impact_summary, completed_at, created_at, updated_at
`

type UpdateActivityProgressParams struct {
	ID                 uuid.UUID `json:"id"`
	ProgressPercentage int32     `json:"progress_percentage"`
	UserID             uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateActivityProgress(ctx context.Context, arg UpdateActivityProgressParams) (Activity, error) {
	row := q.db.QueryRow(ctx, updateActivityProgress, arg.ID, arg.ProgressPercentage, arg.UserID)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LadderID,
		&i.Title,
		&i.Description,
		&i.IsPdiTarget,
		&i.ProgressPercentage,
		&i.ImpactSummary,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
