// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ladder.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createLadderLevel = `-- name: CreateLadderLevel :one
INSERT INTO career_ladder (
    level, xp_reward, technical, expected_results, leadership_scope
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, level, xp_reward, technical, expected_results, leadership_scope
`

type CreateLadderLevelParams struct {
	Level           LadderLevel `json:"level"`
	XpReward        int32       `json:"xp_reward"`
	Technical       string      `json:"technical"`
	ExpectedResults string      `json:"expected_results"`
	LeadershipScope string      `json:"leadership_scope"`
}

func (q *Queries) CreateLadderLevel(ctx context.Context, arg CreateLadderLevelParams) (CareerLadder, error) {
	row := q.db.QueryRow(ctx, createLadderLevel,
		arg.Level,
		arg.XpReward,
		arg.Technical,
		arg.ExpectedResults,
		arg.LeadershipScope,
	)
	var i CareerLadder
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.XpReward,
		&i.Technical,
		&i.ExpectedResults,
		&i.LeadershipScope,
	)
	return i, err
}

const findLadderByLevel = `-- name: FindLadderByLevel :one
SELECT 
    id, 
    level, 
    xp_reward,
    technical, 
    expected_results, 
    leadership_scope
FROM career_ladder 
WHERE level = $1
`

func (q *Queries) FindLadderByLevel(ctx context.Context, level LadderLevel) (CareerLadder, error) {
	row := q.db.QueryRow(ctx, findLadderByLevel, level)
	var i CareerLadder
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.XpReward,
		&i.Technical,
		&i.ExpectedResults,
		&i.LeadershipScope,
	)
	return i, err
}

const findLadderLevel = `-- name: FindLadderLevel :one
SELECT id, level, xp_reward, technical, expected_results, leadership_scope
FROM career_ladder
WHERE id = $1
`

func (q *Queries) FindLadderLevel(ctx context.Context, id uuid.UUID) (CareerLadder, error) {
	row := q.db.QueryRow(ctx, findLadderLevel, id)
	var i CareerLadder
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.XpReward,
		&i.Technical,
		&i.ExpectedResults,
		&i.LeadershipScope,
	)
	return i, err
}

const listEntireLadder = `-- name: ListEntireLadder :many
SELECT id, level, xp_reward, technical, expected_results, leadership_scope
FROM career_ladder
ORDER BY level
`

func (q *Queries) ListEntireLadder(ctx context.Context) ([]CareerLadder, error) {
	rows, err := q.db.Query(ctx, listEntireLadder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CareerLadder
	for rows.Next() {
		var i CareerLadder
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.XpReward,
			&i.Technical,
			&i.ExpectedResults,
			&i.LeadershipScope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLadderXP = `-- name: UpdateLadderXP :exec
UPDATE career_ladder
SET xp_reward = $2
WHERE id = $1
`

type UpdateLadderXPParams struct {
	ID       uuid.UUID `json:"id"`
	XpReward int32     `json:"xp_reward"`
}

func (q *Queries) UpdateLadderXP(ctx context.Context, arg UpdateLadderXPParams) error {
	_, err := q.db.Exec(ctx, updateLadderXP, arg.ID, arg.XpReward)
	return err
}
