// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	FindAllUsers(ctx context.Context) ([]FindAllUsersRow, error)
	FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error)
	FindUserByID(ctx context.Context, id uuid.UUID) (FindUserByIDRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
