// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_pillar.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createActivityPillar = `-- name: CreateActivityPillar :one
INSERT INTO public.activity_pillars
(activity_id, pillar)
VALUES($1, $2)
RETURNING activity_id, pillar
`

type CreateActivityPillarParams struct {
	ActivityID uuid.UUID `json:"activity_id"`
	Pillar     Pillar    `json:"pillar"`
}

func (q *Queries) CreateActivityPillar(ctx context.Context, arg CreateActivityPillarParams) (ActivityPillar, error) {
	row := q.db.QueryRow(ctx, createActivityPillar, arg.ActivityID, arg.Pillar)
	var i ActivityPillar
	err := row.Scan(&i.ActivityID, &i.Pillar)
	return i, err
}
