// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: evaluetion_cycles.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findCurrentCycle = `-- name: FindCurrentCycle :one
SELECT id, name, start_date, end_date, is_active FROM evaluation_cycles 
WHERE CURRENT_DATE BETWEEN start_date AND end_date 
AND is_active = true LIMIT 1
`

func (q *Queries) FindCurrentCycle(ctx context.Context) (EvaluationCycle, error) {
	row := q.db.QueryRow(ctx, findCurrentCycle)
	var i EvaluationCycle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
	)
	return i, err
}

const findPerformanceByPeriod = `-- name: FindPerformanceByPeriod :many
SELECT 
    cl.level,
    SUM(cl.xp_reward)::int as total_xp,
    COUNT(a.id)::int as activity_count
FROM activities a
JOIN career_ladder cl ON a.ladder_id = cl.id
WHERE a.user_id = $1 
  AND a.completed_at BETWEEN $2 AND $3 
  AND a.progress_percentage = 100
GROUP BY cl.level
`

type FindPerformanceByPeriodParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	CompletedAt   pgtype.Date `json:"completed_at"`
	CompletedAt_2 pgtype.Date `json:"completed_at_2"`
}

type FindPerformanceByPeriodRow struct {
	Level         LadderLevel `json:"level"`
	TotalXp       int32       `json:"total_xp"`
	ActivityCount int32       `json:"activity_count"`
}

func (q *Queries) FindPerformanceByPeriod(ctx context.Context, arg FindPerformanceByPeriodParams) ([]FindPerformanceByPeriodRow, error) {
	rows, err := q.db.Query(ctx, findPerformanceByPeriod, arg.UserID, arg.CompletedAt, arg.CompletedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindPerformanceByPeriodRow
	for rows.Next() {
		var i FindPerformanceByPeriodRow
		if err := rows.Scan(&i.Level, &i.TotalXp, &i.ActivityCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPreviousCycle = `-- name: FindPreviousCycle :one
SELECT id, name, start_date, end_date, is_active FROM evaluation_cycles 
WHERE end_date < $1 -- Busca o ciclo que terminou antes do início do atual
ORDER BY end_date DESC LIMIT 1
`

func (q *Queries) FindPreviousCycle(ctx context.Context, endDate pgtype.Date) (EvaluationCycle, error) {
	row := q.db.QueryRow(ctx, findPreviousCycle, endDate)
	var i EvaluationCycle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
	)
	return i, err
}
