// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: initiatives.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUserInitiatives = `-- name: CountUserInitiatives :one
SELECT COUNT(*) FROM initiatives WHERE user_id = $1
`

func (q *Queries) CountUserInitiatives(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserInitiatives, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInitiative = `-- name: CreateInitiative :one
INSERT INTO initiatives (
    user_id, title, description, is_pdi_target
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, title, description, is_pdi_target, progress_percentage, completed_at, created_at, updated_at
`

type CreateInitiativeParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	IsPdiTarget bool        `json:"is_pdi_target"`
}

func (q *Queries) CreateInitiative(ctx context.Context, arg CreateInitiativeParams) (Initiative, error) {
	row := q.db.QueryRow(ctx, createInitiative,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.IsPdiTarget,
	)
	var i Initiative
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.IsPdiTarget,
		&i.ProgressPercentage,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInitiative = `-- name: DeleteInitiative :exec
DELETE FROM initiatives
WHERE id = $1 AND user_id = $2
`

type DeleteInitiativeParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteInitiative(ctx context.Context, arg DeleteInitiativeParams) error {
	_, err := q.db.Exec(ctx, deleteInitiative, arg.ID, arg.UserID)
	return err
}

const findCurrentTargetLevel = `-- name: FindCurrentTargetLevel :one
SELECT
    lt.target as level,
    cl.id as ladder_id
FROM level_target lt
JOIN career_ladder cl ON cl.level = lt.target
WHERE lt.user_id = $1 AND lt.year = $2
LIMIT 1
`

type FindCurrentTargetLevelParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Year   int32       `json:"year"`
}

type FindCurrentTargetLevelRow struct {
	Level    LadderLevel `json:"level"`
	LadderID uuid.UUID   `json:"ladder_id"`
}

func (q *Queries) FindCurrentTargetLevel(ctx context.Context, arg FindCurrentTargetLevelParams) (FindCurrentTargetLevelRow, error) {
	row := q.db.QueryRow(ctx, findCurrentTargetLevel, arg.UserID, arg.Year)
	var i FindCurrentTargetLevelRow
	err := row.Scan(&i.Level, &i.LadderID)
	return i, err
}

const findDetailedInitiativeReport = `-- name: FindDetailedInitiativeReport :many
SELECT
    t.id,
    t.title,
    t.execution,
    t.impact_summary,
    t.progress_percentage,
    i.is_pdi_target,
    cl.level,
    cl.xp_reward,
    (
        SELECT array_agg(tp.pillar::text)
        FROM task_pillars tp
        WHERE tp.task_id = t.id
    ) as pillars
FROM tasks t
JOIN initiatives i ON t.initiative_id = i.id
JOIN career_ladder cl ON t.ladder_id = cl.id
WHERE i.user_id = $1
ORDER BY t.progress_percentage DESC, t.created_at DESC
`

type FindDetailedInitiativeReportRow struct {
	ID                 uuid.UUID   `json:"id"`
	Title              string      `json:"title"`
	Execution          pgtype.Text `json:"execution"`
	ImpactSummary      pgtype.Text `json:"impact_summary"`
	ProgressPercentage int32       `json:"progress_percentage"`
	IsPdiTarget        bool        `json:"is_pdi_target"`
	Level              LadderLevel `json:"level"`
	XpReward           int32       `json:"xp_reward"`
	Pillars            interface{} `json:"pillars"`
}

func (q *Queries) FindDetailedInitiativeReport(ctx context.Context, userID uuid.UUID) ([]FindDetailedInitiativeReportRow, error) {
	rows, err := q.db.Query(ctx, findDetailedInitiativeReport, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindDetailedInitiativeReportRow
	for rows.Next() {
		var i FindDetailedInitiativeReportRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Execution,
			&i.ImpactSummary,
			&i.ProgressPercentage,
			&i.IsPdiTarget,
			&i.Level,
			&i.XpReward,
			&i.Pillars,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findGapAnalysis = `-- name: FindGapAnalysis :many
SELECT
    cl.level,
    tp.pillar::text as pillar,
    SUM(CASE WHEN i.is_pdi_target = true THEN cl.xp_reward ELSE 0 END)::int as target_xp,
    SUM(CASE WHEN t.progress_percentage = 100 THEN cl.xp_reward ELSE 0 END)::int as achieved_xp,
    (SUM(CASE WHEN i.is_pdi_target = true THEN cl.xp_reward ELSE 0 END) -
     SUM(CASE WHEN t.progress_percentage = 100 THEN cl.xp_reward ELSE 0 END))::int as gap_xp,
    CASE
        WHEN SUM(CASE WHEN i.is_pdi_target = true THEN cl.xp_reward ELSE 0 END) = 0 THEN 0
        ELSE ROUND(
            (SUM(CASE WHEN t.progress_percentage = 100 THEN cl.xp_reward ELSE 0 END)::float /
             SUM(CASE WHEN i.is_pdi_target = true THEN cl.xp_reward ELSE 0 END)::float) * 100
        )::int
    END as completion_percentage
FROM tasks t
JOIN initiatives i ON t.initiative_id = i.id
JOIN career_ladder cl ON t.ladder_id = cl.id
JOIN task_pillars tp ON tp.task_id = t.id
WHERE i.user_id = $1
  AND EXTRACT(YEAR FROM t.created_at)::int = $2::int
  AND i.is_pdi_target = true
GROUP BY cl.level, tp.pillar
HAVING SUM(CASE WHEN i.is_pdi_target = true THEN cl.xp_reward ELSE 0 END) > 0
ORDER BY cl.level, tp.pillar
`

type FindGapAnalysisParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 int32     `json:"column_2"`
}

type FindGapAnalysisRow struct {
	Level                LadderLevel `json:"level"`
	Pillar               string      `json:"pillar"`
	TargetXp             int32       `json:"target_xp"`
	AchievedXp           int32       `json:"achieved_xp"`
	GapXp                int32       `json:"gap_xp"`
	CompletionPercentage int32       `json:"completion_percentage"`
}

func (q *Queries) FindGapAnalysis(ctx context.Context, arg FindGapAnalysisParams) ([]FindGapAnalysisRow, error) {
	rows, err := q.db.Query(ctx, findGapAnalysis, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindGapAnalysisRow
	for rows.Next() {
		var i FindGapAnalysisRow
		if err := rows.Scan(
			&i.Level,
			&i.Pillar,
			&i.TargetXp,
			&i.AchievedXp,
			&i.GapXp,
			&i.CompletionPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findInitiativeByID = `-- name: FindInitiativeByID :one
SELECT id, title, description, is_pdi_target, progress_percentage, user_id, created_at
FROM initiatives
WHERE id = $1 AND user_id = $2
`

type FindInitiativeByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type FindInitiativeByIDRow struct {
	ID                 uuid.UUID   `json:"id"`
	Title              string      `json:"title"`
	Description        pgtype.Text `json:"description"`
	IsPdiTarget        bool        `json:"is_pdi_target"`
	ProgressPercentage int32       `json:"progress_percentage"`
	UserID             uuid.UUID   `json:"user_id"`
	CreatedAt          pgtype.Date `json:"created_at"`
}

func (q *Queries) FindInitiativeByID(ctx context.Context, arg FindInitiativeByIDParams) (FindInitiativeByIDRow, error) {
	row := q.db.QueryRow(ctx, findInitiativeByID, arg.ID, arg.UserID)
	var i FindInitiativeByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsPdiTarget,
		&i.ProgressPercentage,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const findInitiativeComposition = `-- name: FindInitiativeComposition :many
SELECT
    cl.level,
    COUNT(t.id)::int as total_activities,
    SUM(cl.xp_reward)::int as total_xp
FROM tasks t
JOIN initiatives i ON t.initiative_id = i.id
JOIN career_ladder cl ON t.ladder_id = cl.id
WHERE i.user_id = $1 AND t.progress_percentage = 100
GROUP BY cl.level
ORDER BY cl.level ASC
`

type FindInitiativeCompositionRow struct {
	Level           LadderLevel `json:"level"`
	TotalActivities int32       `json:"total_activities"`
	TotalXp         int32       `json:"total_xp"`
}

func (q *Queries) FindInitiativeComposition(ctx context.Context, userID uuid.UUID) ([]FindInitiativeCompositionRow, error) {
	rows, err := q.db.Query(ctx, findInitiativeComposition, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindInitiativeCompositionRow
	for rows.Next() {
		var i FindInitiativeCompositionRow
		if err := rows.Scan(&i.Level, &i.TotalActivities, &i.TotalXp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPdiDashboard = `-- name: FindPdiDashboard :many
SELECT
    cl.level,
    tp.pillar::text as pillar,
    SUM(CASE WHEN i.is_pdi_target = true THEN cl.xp_reward ELSE 0 END)::int as total_pdi_planned,
    SUM(CASE WHEN t.progress_percentage = 100 THEN cl.xp_reward ELSE 0 END)::int as total_achieved,
    SUM(CASE WHEN t.progress_percentage = 100 AND i.is_pdi_target = false THEN cl.xp_reward ELSE 0 END)::int as overdelivery_xp,
    COUNT(t.id)::int as activity_count
FROM initiatives i
JOIN tasks t ON t.initiative_id = i.id
JOIN task_pillars tp ON tp.task_id = t.id
JOIN career_ladder cl ON t.ladder_id = cl.id
WHERE i.user_id = $1
GROUP BY cl.level, tp.pillar
ORDER BY cl.level ASC
`

type FindPdiDashboardRow struct {
	Level           LadderLevel `json:"level"`
	Pillar          string      `json:"pillar"`
	TotalPdiPlanned int32       `json:"total_pdi_planned"`
	TotalAchieved   int32       `json:"total_achieved"`
	OverdeliveryXp  int32       `json:"overdelivery_xp"`
	ActivityCount   int32       `json:"activity_count"`
}

func (q *Queries) FindPdiDashboard(ctx context.Context, userID uuid.UUID) ([]FindPdiDashboardRow, error) {
	rows, err := q.db.Query(ctx, findPdiDashboard, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindPdiDashboardRow
	for rows.Next() {
		var i FindPdiDashboardRow
		if err := rows.Scan(
			&i.Level,
			&i.Pillar,
			&i.TotalPdiPlanned,
			&i.TotalAchieved,
			&i.OverdeliveryXp,
			&i.ActivityCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserInitiatives = `-- name: ListUserInitiatives :many
SELECT
    i.id,
    i.user_id,
    i.title,
    i.description,
    i.progress_percentage,
    i.is_pdi_target,
    i.completed_at,
    i.created_at,
    (SELECT COUNT(*) FROM tasks WHERE initiative_id = i.id)::int as task_count,
    (SELECT COUNT(*) > 0 FROM tasks WHERE initiative_id = i.id AND is_extra = true)::bool as has_extra
FROM initiatives i
WHERE i.user_id = $1
ORDER BY i.progress_percentage ASC, i.created_at DESC
`

type ListUserInitiativesRow struct {
	ID                 uuid.UUID   `json:"id"`
	UserID             uuid.UUID   `json:"user_id"`
	Title              string      `json:"title"`
	Description        pgtype.Text `json:"description"`
	ProgressPercentage int32       `json:"progress_percentage"`
	IsPdiTarget        bool        `json:"is_pdi_target"`
	CompletedAt        pgtype.Date `json:"completed_at"`
	CreatedAt          pgtype.Date `json:"created_at"`
	TaskCount          int32       `json:"task_count"`
	HasExtra           bool        `json:"has_extra"`
}

func (q *Queries) ListUserInitiatives(ctx context.Context, userID uuid.UUID) ([]ListUserInitiativesRow, error) {
	rows, err := q.db.Query(ctx, listUserInitiatives, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserInitiativesRow
	for rows.Next() {
		var i ListUserInitiativesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.ProgressPercentage,
			&i.IsPdiTarget,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.TaskCount,
			&i.HasExtra,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInitiative = `-- name: UpdateInitiative :one
UPDATE initiatives
SET
    title = $2,
    description = $3,
    is_pdi_target = $4,
    updated_at = NOW()
WHERE id = $1 AND user_id = $5
RETURNING id, user_id, title, description, is_pdi_target, progress_percentage, completed_at, created_at, updated_at
`

type UpdateInitiativeParams struct {
	ID          uuid.UUID   `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	IsPdiTarget bool        `json:"is_pdi_target"`
	UserID      uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateInitiative(ctx context.Context, arg UpdateInitiativeParams) (Initiative, error) {
	row := q.db.QueryRow(ctx, updateInitiative,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.IsPdiTarget,
		arg.UserID,
	)
	var i Initiative
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.IsPdiTarget,
		&i.ProgressPercentage,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
