// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: initiative_pillars.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createInitiativePillar = `-- name: CreateInitiativePillar :one
INSERT INTO initiative_pillars (initiative_id, pillar)
VALUES ($1, $2)
RETURNING initiative_id, pillar
`

type CreateInitiativePillarParams struct {
	InitiativeID uuid.UUID `json:"initiative_id"`
	Pillar       Pillar    `json:"pillar"`
}

func (q *Queries) CreateInitiativePillar(ctx context.Context, arg CreateInitiativePillarParams) (InitiativePillar, error) {
	row := q.db.QueryRow(ctx, createInitiativePillar, arg.InitiativeID, arg.Pillar)
	var i InitiativePillar
	err := row.Scan(&i.InitiativeID, &i.Pillar)
	return i, err
}
