// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: initiatives.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUserInitiatives = `-- name: CountUserInitiatives :one
SELECT COUNT(*) FROM initiatives WHERE user_id = $1
`

func (q *Queries) CountUserInitiatives(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserInitiatives, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInitiative = `-- name: CreateInitiative :one
INSERT INTO initiatives (
    user_id, 
    ladder_id, 
    title, 
    description, 
    progress_percentage, 
    impact_summary, 
    is_pdi_target
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, ladder_id, title, description, is_pdi_target, progress_percentage, impact_summary, completed_at, created_at, updated_at
`

type CreateInitiativeParams struct {
	UserID             uuid.UUID   `json:"user_id"`
	LadderID           uuid.UUID   `json:"ladder_id"`
	Title              string      `json:"title"`
	Description        pgtype.Text `json:"description"`
	ProgressPercentage int32       `json:"progress_percentage"`
	ImpactSummary      pgtype.Text `json:"impact_summary"`
	IsPdiTarget        bool        `json:"is_pdi_target"`
}

func (q *Queries) CreateInitiative(ctx context.Context, arg CreateInitiativeParams) (Initiative, error) {
	row := q.db.QueryRow(ctx, createInitiative,
		arg.UserID,
		arg.LadderID,
		arg.Title,
		arg.Description,
		arg.ProgressPercentage,
		arg.ImpactSummary,
		arg.IsPdiTarget,
	)
	var i Initiative
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LadderID,
		&i.Title,
		&i.Description,
		&i.IsPdiTarget,
		&i.ProgressPercentage,
		&i.ImpactSummary,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInitiative = `-- name: DeleteInitiative :exec
DELETE FROM initiatives 
WHERE id = $1 AND user_id = $2
`

type DeleteInitiativeParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteInitiative(ctx context.Context, arg DeleteInitiativeParams) error {
	_, err := q.db.Exec(ctx, deleteInitiative, arg.ID, arg.UserID)
	return err
}

const findCurrentTargetLevel = `-- name: FindCurrentTargetLevel :one
SELECT 
    cl.level,
    cl.id as ladder_id
FROM xp_target xt
JOIN career_ladder cl ON xt.ladder_id = cl.id
WHERE xt.year = $1
LIMIT 1
`

type FindCurrentTargetLevelRow struct {
	Level    LadderLevel `json:"level"`
	LadderID uuid.UUID   `json:"ladder_id"`
}

func (q *Queries) FindCurrentTargetLevel(ctx context.Context, year int32) (FindCurrentTargetLevelRow, error) {
	row := q.db.QueryRow(ctx, findCurrentTargetLevel, year)
	var i FindCurrentTargetLevelRow
	err := row.Scan(&i.Level, &i.LadderID)
	return i, err
}

const findDetailedInitiativeReport = `-- name: FindDetailedInitiativeReport :many
SELECT 
    a.id,
    a.title,
    a.progress_percentage,
    a.is_pdi_target,
    cl.level,
    cl.xp_reward,
    (
        SELECT array_agg(ap.pillar::text)
        FROM initiative_pillars ap
        WHERE ap.initiative_id = a.id
    ) as pillars
FROM initiatives a
JOIN career_ladder cl ON a.ladder_id = cl.id
WHERE a.user_id = $1
ORDER BY a.progress_percentage DESC, a.created_at DESC
`

type FindDetailedInitiativeReportRow struct {
	ID                 uuid.UUID   `json:"id"`
	Title              string      `json:"title"`
	ProgressPercentage int32       `json:"progress_percentage"`
	IsPdiTarget        bool        `json:"is_pdi_target"`
	Level              LadderLevel `json:"level"`
	XpReward           int32       `json:"xp_reward"`
	Pillars            interface{} `json:"pillars"`
}

func (q *Queries) FindDetailedInitiativeReport(ctx context.Context, userID uuid.UUID) ([]FindDetailedInitiativeReportRow, error) {
	rows, err := q.db.Query(ctx, findDetailedInitiativeReport, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindDetailedInitiativeReportRow
	for rows.Next() {
		var i FindDetailedInitiativeReportRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ProgressPercentage,
			&i.IsPdiTarget,
			&i.Level,
			&i.XpReward,
			&i.Pillars,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findGapAnalysis = `-- name: FindGapAnalysis :many
SELECT 
    cl.level,
    ap.pillar::text as pillar,
    SUM(CASE WHEN a.is_pdi_target = true THEN cl.xp_reward ELSE 0 END)::int as target_xp,
    SUM(CASE WHEN a.progress_percentage = 100 THEN cl.xp_reward ELSE 0 END)::int as achieved_xp,
    (SUM(CASE WHEN a.is_pdi_target = true THEN cl.xp_reward ELSE 0 END) - 
     SUM(CASE WHEN a.progress_percentage = 100 THEN cl.xp_reward ELSE 0 END))::int as gap_xp,
    CASE 
        WHEN SUM(CASE WHEN a.is_pdi_target = true THEN cl.xp_reward ELSE 0 END) = 0 THEN 0
        ELSE ROUND(
            (SUM(CASE WHEN a.progress_percentage = 100 THEN cl.xp_reward ELSE 0 END)::float / 
             SUM(CASE WHEN a.is_pdi_target = true THEN cl.xp_reward ELSE 0 END)::float) * 100
        )::int
    END as completion_percentage
FROM initiatives a
JOIN career_ladder cl ON a.ladder_id = cl.id
JOIN initiative_pillars ap ON a.id = ap.initiative_id
WHERE a.user_id = $1 
  AND EXTRACT(YEAR FROM a.created_at)::int = $2::int
  AND a.is_pdi_target = true
GROUP BY cl.level, ap.pillar
HAVING SUM(CASE WHEN a.is_pdi_target = true THEN cl.xp_reward ELSE 0 END) > 0
ORDER BY cl.level, ap.pillar
`

type FindGapAnalysisParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 int32     `json:"column_2"`
}

type FindGapAnalysisRow struct {
	Level                LadderLevel `json:"level"`
	Pillar               string      `json:"pillar"`
	TargetXp             int32       `json:"target_xp"`
	AchievedXp           int32       `json:"achieved_xp"`
	GapXp                int32       `json:"gap_xp"`
	CompletionPercentage int32       `json:"completion_percentage"`
}

func (q *Queries) FindGapAnalysis(ctx context.Context, arg FindGapAnalysisParams) ([]FindGapAnalysisRow, error) {
	rows, err := q.db.Query(ctx, findGapAnalysis, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindGapAnalysisRow
	for rows.Next() {
		var i FindGapAnalysisRow
		if err := rows.Scan(
			&i.Level,
			&i.Pillar,
			&i.TargetXp,
			&i.AchievedXp,
			&i.GapXp,
			&i.CompletionPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findInitiativeByID = `-- name: FindInitiativeByID :one
SELECT
    a.id,
    a.title,
    a.description,
    a.impact_summary,
    a.is_pdi_target,
    a.progress_percentage,
    a.ladder_id,
    a.user_id
FROM initiatives a 
WHERE a.id = $1 AND a.user_id = $2
`

type FindInitiativeByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type FindInitiativeByIDRow struct {
	ID                 uuid.UUID   `json:"id"`
	Title              string      `json:"title"`
	Description        pgtype.Text `json:"description"`
	ImpactSummary      pgtype.Text `json:"impact_summary"`
	IsPdiTarget        bool        `json:"is_pdi_target"`
	ProgressPercentage int32       `json:"progress_percentage"`
	LadderID           uuid.UUID   `json:"ladder_id"`
	UserID             uuid.UUID   `json:"user_id"`
}

func (q *Queries) FindInitiativeByID(ctx context.Context, arg FindInitiativeByIDParams) (FindInitiativeByIDRow, error) {
	row := q.db.QueryRow(ctx, findInitiativeByID, arg.ID, arg.UserID)
	var i FindInitiativeByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ImpactSummary,
		&i.IsPdiTarget,
		&i.ProgressPercentage,
		&i.LadderID,
		&i.UserID,
	)
	return i, err
}

const findInitiativeComposition = `-- name: FindInitiativeComposition :many
SELECT 
    cl.level,
    COUNT(a.id)::int as total_activities,
    SUM(cl.xp_reward)::int as total_xp
FROM initiatives a
JOIN career_ladder cl ON a.ladder_id = cl.id
WHERE a.user_id = $1 AND a.progress_percentage = 100
GROUP BY cl.level
ORDER BY cl.level ASC
`

type FindInitiativeCompositionRow struct {
	Level           LadderLevel `json:"level"`
	TotalActivities int32       `json:"total_activities"`
	TotalXp         int32       `json:"total_xp"`
}

func (q *Queries) FindInitiativeComposition(ctx context.Context, userID uuid.UUID) ([]FindInitiativeCompositionRow, error) {
	rows, err := q.db.Query(ctx, findInitiativeComposition, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindInitiativeCompositionRow
	for rows.Next() {
		var i FindInitiativeCompositionRow
		if err := rows.Scan(&i.Level, &i.TotalActivities, &i.TotalXp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findInitiativeDetail = `-- name: FindInitiativeDetail :one
SELECT 
    a.id, a.title, a.progress_percentage, a.impact_summary,
    cl.level
FROM initiatives a
JOIN career_ladder cl ON a.ladder_id = cl.id
WHERE a.id = $1 AND a.user_id = $2
`

type FindInitiativeDetailParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type FindInitiativeDetailRow struct {
	ID                 uuid.UUID   `json:"id"`
	Title              string      `json:"title"`
	ProgressPercentage int32       `json:"progress_percentage"`
	ImpactSummary      pgtype.Text `json:"impact_summary"`
	Level              LadderLevel `json:"level"`
}

func (q *Queries) FindInitiativeDetail(ctx context.Context, arg FindInitiativeDetailParams) (FindInitiativeDetailRow, error) {
	row := q.db.QueryRow(ctx, findInitiativeDetail, arg.ID, arg.UserID)
	var i FindInitiativeDetailRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ProgressPercentage,
		&i.ImpactSummary,
		&i.Level,
	)
	return i, err
}

const findInitiativeWithLadder = `-- name: FindInitiativeWithLadder :one
SELECT 
    a.id, 
    a.user_id, 
    a.ladder_id, 
    a.title, 
    a.description, 
    a.progress_percentage, 
    a.impact_summary, 
    a.completed_at, 
    a.created_at,
    cl.level, 
    cl.xp_reward, 
    cl.technical,
    cl.expected_results,
    cl.leadership_scope
FROM initiatives a
JOIN career_ladder cl ON a.ladder_id = cl.id
WHERE a.id = $1 AND a.user_id = $2
`

type FindInitiativeWithLadderParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type FindInitiativeWithLadderRow struct {
	ID                 uuid.UUID   `json:"id"`
	UserID             uuid.UUID   `json:"user_id"`
	LadderID           uuid.UUID   `json:"ladder_id"`
	Title              string      `json:"title"`
	Description        pgtype.Text `json:"description"`
	ProgressPercentage int32       `json:"progress_percentage"`
	ImpactSummary      pgtype.Text `json:"impact_summary"`
	CompletedAt        pgtype.Date `json:"completed_at"`
	CreatedAt          pgtype.Date `json:"created_at"`
	Level              LadderLevel `json:"level"`
	XpReward           int32       `json:"xp_reward"`
	Technical          string      `json:"technical"`
	ExpectedResults    string      `json:"expected_results"`
	LeadershipScope    string      `json:"leadership_scope"`
}

func (q *Queries) FindInitiativeWithLadder(ctx context.Context, arg FindInitiativeWithLadderParams) (FindInitiativeWithLadderRow, error) {
	row := q.db.QueryRow(ctx, findInitiativeWithLadder, arg.ID, arg.UserID)
	var i FindInitiativeWithLadderRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LadderID,
		&i.Title,
		&i.Description,
		&i.ProgressPercentage,
		&i.ImpactSummary,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.Level,
		&i.XpReward,
		&i.Technical,
		&i.ExpectedResults,
		&i.LeadershipScope,
	)
	return i, err
}

const findPdiDashboard = `-- name: FindPdiDashboard :many
SELECT 
    cl.level,
    ap.pillar::text as pillar,
    SUM(CASE WHEN a.is_pdi_target = true THEN cl.xp_reward ELSE 0 END)::int as total_pdi_planned,
    SUM(CASE WHEN a.progress_percentage = 100 THEN cl.xp_reward ELSE 0 END)::int as total_achieved,
    SUM(CASE WHEN a.progress_percentage = 100 AND a.is_pdi_target = false THEN cl.xp_reward ELSE 0 END)::int as overdelivery_xp,
    COUNT(a.id)::int as activity_count
FROM initiatives a
JOIN initiative_pillars ap ON a.id = ap.initiative_id
JOIN career_ladder cl ON a.ladder_id = cl.id
WHERE a.user_id = $1
GROUP BY cl.level, ap.pillar
ORDER BY cl.level ASC
`

type FindPdiDashboardRow struct {
	Level           LadderLevel `json:"level"`
	Pillar          string      `json:"pillar"`
	TotalPdiPlanned int32       `json:"total_pdi_planned"`
	TotalAchieved   int32       `json:"total_achieved"`
	OverdeliveryXp  int32       `json:"overdelivery_xp"`
	ActivityCount   int32       `json:"activity_count"`
}

func (q *Queries) FindPdiDashboard(ctx context.Context, userID uuid.UUID) ([]FindPdiDashboardRow, error) {
	rows, err := q.db.Query(ctx, findPdiDashboard, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindPdiDashboardRow
	for rows.Next() {
		var i FindPdiDashboardRow
		if err := rows.Scan(
			&i.Level,
			&i.Pillar,
			&i.TotalPdiPlanned,
			&i.TotalAchieved,
			&i.OverdeliveryXp,
			&i.ActivityCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserInitiatives = `-- name: FindUserInitiatives :many
SELECT 
    a.id,
    a.title,
    a.progress_percentage,
    a.is_pdi_target,
    cl.level,
    COALESCE(string_agg(ap.pillar::text, ', '), '') as pillars
FROM initiatives a
JOIN career_ladder cl ON a.ladder_id = cl.id
LEFT JOIN initiative_pillars ap ON a.id = ap.initiative_id
WHERE a.user_id = $1
GROUP BY a.id, cl.level
ORDER BY a.created_at DESC
`

type FindUserInitiativesRow struct {
	ID                 uuid.UUID   `json:"id"`
	Title              string      `json:"title"`
	ProgressPercentage int32       `json:"progress_percentage"`
	IsPdiTarget        bool        `json:"is_pdi_target"`
	Level              LadderLevel `json:"level"`
	Pillars            interface{} `json:"pillars"`
}

func (q *Queries) FindUserInitiatives(ctx context.Context, userID uuid.UUID) ([]FindUserInitiativesRow, error) {
	rows, err := q.db.Query(ctx, findUserInitiatives, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindUserInitiativesRow
	for rows.Next() {
		var i FindUserInitiativesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ProgressPercentage,
			&i.IsPdiTarget,
			&i.Level,
			&i.Pillars,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserInitiatives = `-- name: ListUserInitiatives :many
SELECT 
    a.id, 
    a.user_id, 
    a.ladder_id, 
    a.title, 
    a.description, 
    a.progress_percentage, 
    a.impact_summary, 
    a.is_pdi_target,
    a.completed_at, 
    a.created_at,
    (SELECT COUNT(*) FROM tasks WHERE initiative_id = a.id)::int as task_count
FROM initiatives a
WHERE a.user_id = $1 
ORDER BY a.created_at DESC
`

type ListUserInitiativesRow struct {
	ID                 uuid.UUID   `json:"id"`
	UserID             uuid.UUID   `json:"user_id"`
	LadderID           uuid.UUID   `json:"ladder_id"`
	Title              string      `json:"title"`
	Description        pgtype.Text `json:"description"`
	ProgressPercentage int32       `json:"progress_percentage"`
	ImpactSummary      pgtype.Text `json:"impact_summary"`
	IsPdiTarget        bool        `json:"is_pdi_target"`
	CompletedAt        pgtype.Date `json:"completed_at"`
	CreatedAt          pgtype.Date `json:"created_at"`
	TaskCount          int32       `json:"task_count"`
}

func (q *Queries) ListUserInitiatives(ctx context.Context, userID uuid.UUID) ([]ListUserInitiativesRow, error) {
	rows, err := q.db.Query(ctx, listUserInitiatives, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserInitiativesRow
	for rows.Next() {
		var i ListUserInitiativesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LadderID,
			&i.Title,
			&i.Description,
			&i.ProgressPercentage,
			&i.ImpactSummary,
			&i.IsPdiTarget,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.TaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserInitiativesPaginated = `-- name: ListUserInitiativesPaginated :many
SELECT 
    id, 
    user_id, 
    ladder_id, 
    title, 
    description, 
    progress_percentage, 
    impact_summary, 
    completed_at, 
    created_at
FROM initiatives 
WHERE user_id = $1 
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserInitiativesPaginatedParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListUserInitiativesPaginatedRow struct {
	ID                 uuid.UUID   `json:"id"`
	UserID             uuid.UUID   `json:"user_id"`
	LadderID           uuid.UUID   `json:"ladder_id"`
	Title              string      `json:"title"`
	Description        pgtype.Text `json:"description"`
	ProgressPercentage int32       `json:"progress_percentage"`
	ImpactSummary      pgtype.Text `json:"impact_summary"`
	CompletedAt        pgtype.Date `json:"completed_at"`
	CreatedAt          pgtype.Date `json:"created_at"`
}

func (q *Queries) ListUserInitiativesPaginated(ctx context.Context, arg ListUserInitiativesPaginatedParams) ([]ListUserInitiativesPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listUserInitiativesPaginated, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserInitiativesPaginatedRow
	for rows.Next() {
		var i ListUserInitiativesPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LadderID,
			&i.Title,
			&i.Description,
			&i.ProgressPercentage,
			&i.ImpactSummary,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInitiative = `-- name: UpdateInitiative :one
UPDATE initiatives 
SET 
    title = $2,
    description = $3,
    progress_percentage = $4,
    impact_summary = $5,
    is_pdi_target = $6,
    updated_at = NOW()
WHERE id = $1 AND user_id = $7
RETURNING id, user_id, ladder_id, title, description, is_pdi_target, progress_percentage, impact_summary, completed_at, created_at, updated_at
`

type UpdateInitiativeParams struct {
	ID                 uuid.UUID   `json:"id"`
	Title              string      `json:"title"`
	Description        pgtype.Text `json:"description"`
	ProgressPercentage int32       `json:"progress_percentage"`
	ImpactSummary      pgtype.Text `json:"impact_summary"`
	IsPdiTarget        bool        `json:"is_pdi_target"`
	UserID             uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateInitiative(ctx context.Context, arg UpdateInitiativeParams) (Initiative, error) {
	row := q.db.QueryRow(ctx, updateInitiative,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ProgressPercentage,
		arg.ImpactSummary,
		arg.IsPdiTarget,
		arg.UserID,
	)
	var i Initiative
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LadderID,
		&i.Title,
		&i.Description,
		&i.IsPdiTarget,
		&i.ProgressPercentage,
		&i.ImpactSummary,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInitiativeProgress = `-- name: UpdateInitiativeProgress :one
UPDATE initiatives 
SET 
    progress_percentage = $2,
    updated_at = NOW()
WHERE id = $1 AND user_id = $3
RETURNING id, user_id, ladder_id, title, description, is_pdi_target, progress_percentage, impact_summary, completed_at, created_at, updated_at
`

type UpdateInitiativeProgressParams struct {
	ID                 uuid.UUID `json:"id"`
	ProgressPercentage int32     `json:"progress_percentage"`
	UserID             uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateInitiativeProgress(ctx context.Context, arg UpdateInitiativeProgressParams) (Initiative, error) {
	row := q.db.QueryRow(ctx, updateInitiativeProgress, arg.ID, arg.ProgressPercentage, arg.UserID)
	var i Initiative
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LadderID,
		&i.Title,
		&i.Description,
		&i.IsPdiTarget,
		&i.ProgressPercentage,
		&i.ImpactSummary,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
