// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: level_target.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLevelTarget = `-- name: CreateLevelTarget :one
INSERT INTO level_target (user_id, target, year)
VALUES ($1, $2, $3)
RETURNING id, year, target, user_id
`

type CreateLevelTargetParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Target LadderLevel `json:"target"`
	Year   int32       `json:"year"`
}

func (q *Queries) CreateLevelTarget(ctx context.Context, arg CreateLevelTargetParams) (LevelTarget, error) {
	row := q.db.QueryRow(ctx, createLevelTarget, arg.UserID, arg.Target, arg.Year)
	var i LevelTarget
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Target,
		&i.UserID,
	)
	return i, err
}

const deleteLevelTarget = `-- name: DeleteLevelTarget :exec
DELETE FROM level_target WHERE id = $1 AND user_id = $2
`

type DeleteLevelTargetParams struct {
	ID     uuid.UUID   `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteLevelTarget(ctx context.Context, arg DeleteLevelTargetParams) error {
	_, err := q.db.Exec(ctx, deleteLevelTarget, arg.ID, arg.UserID)
	return err
}

const findLevelTargetByUserAndYear = `-- name: FindLevelTargetByUserAndYear :one
SELECT id, user_id, target, year
FROM level_target
WHERE user_id = $1 AND year = $2
`

type FindLevelTargetByUserAndYearParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Year   int32       `json:"year"`
}

type FindLevelTargetByUserAndYearRow struct {
	ID     uuid.UUID   `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Target LadderLevel `json:"target"`
	Year   int32       `json:"year"`
}

func (q *Queries) FindLevelTargetByUserAndYear(ctx context.Context, arg FindLevelTargetByUserAndYearParams) (FindLevelTargetByUserAndYearRow, error) {
	row := q.db.QueryRow(ctx, findLevelTargetByUserAndYear, arg.UserID, arg.Year)
	var i FindLevelTargetByUserAndYearRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Target,
		&i.Year,
	)
	return i, err
}

const listLevelTargetsByUser = `-- name: ListLevelTargetsByUser :many
SELECT id, user_id, target, year
FROM level_target
WHERE user_id = $1
ORDER BY year DESC
`

type ListLevelTargetsByUserRow struct {
	ID     uuid.UUID   `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Target LadderLevel `json:"target"`
	Year   int32       `json:"year"`
}

func (q *Queries) ListLevelTargetsByUser(ctx context.Context, userID pgtype.UUID) ([]ListLevelTargetsByUserRow, error) {
	rows, err := q.db.Query(ctx, listLevelTargetsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLevelTargetsByUserRow
	for rows.Next() {
		var i ListLevelTargetsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Target,
			&i.Year,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLevelTarget = `-- name: UpsertLevelTarget :one
INSERT INTO level_target (user_id, target, year)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, year) DO UPDATE SET target = $2
RETURNING id, year, target, user_id
`

type UpsertLevelTargetParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Target LadderLevel `json:"target"`
	Year   int32       `json:"year"`
}

func (q *Queries) UpsertLevelTarget(ctx context.Context, arg UpsertLevelTargetParams) (LevelTarget, error) {
	row := q.db.QueryRow(ctx, upsertLevelTarget, arg.UserID, arg.Target, arg.Year)
	var i LevelTarget
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Target,
		&i.UserID,
	)
	return i, err
}
