// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: level_target.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createLevelTarget = `-- name: CreateLevelTarget :one
INSERT INTO level_target (target, year)
VALUES ($1, $2)
RETURNING id, year, target
`

type CreateLevelTargetParams struct {
	Target LadderLevel `json:"target"`
	Year   int32       `json:"year"`
}

func (q *Queries) CreateLevelTarget(ctx context.Context, arg CreateLevelTargetParams) (LevelTarget, error) {
	row := q.db.QueryRow(ctx, createLevelTarget, arg.Target, arg.Year)
	var i LevelTarget
	err := row.Scan(&i.ID, &i.Year, &i.Target)
	return i, err
}

const deleteLevelTarget = `-- name: DeleteLevelTarget :exec
DELETE FROM level_target WHERE id = $1
`

func (q *Queries) DeleteLevelTarget(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLevelTarget, id)
	return err
}

const findLevelTargetByID = `-- name: FindLevelTargetByID :one
SELECT id, target, year
FROM level_target
WHERE id = $1
`

type FindLevelTargetByIDRow struct {
	ID     uuid.UUID   `json:"id"`
	Target LadderLevel `json:"target"`
	Year   int32       `json:"year"`
}

func (q *Queries) FindLevelTargetByID(ctx context.Context, id uuid.UUID) (FindLevelTargetByIDRow, error) {
	row := q.db.QueryRow(ctx, findLevelTargetByID, id)
	var i FindLevelTargetByIDRow
	err := row.Scan(&i.ID, &i.Target, &i.Year)
	return i, err
}

const findLevelTargetByYear = `-- name: FindLevelTargetByYear :one
SELECT id, target, year
FROM level_target
WHERE year = $1
`

type FindLevelTargetByYearRow struct {
	ID     uuid.UUID   `json:"id"`
	Target LadderLevel `json:"target"`
	Year   int32       `json:"year"`
}

func (q *Queries) FindLevelTargetByYear(ctx context.Context, year int32) (FindLevelTargetByYearRow, error) {
	row := q.db.QueryRow(ctx, findLevelTargetByYear, year)
	var i FindLevelTargetByYearRow
	err := row.Scan(&i.ID, &i.Target, &i.Year)
	return i, err
}

const listLevelTargets = `-- name: ListLevelTargets :many
SELECT id, target, year
FROM level_target
ORDER BY year DESC
`

type ListLevelTargetsRow struct {
	ID     uuid.UUID   `json:"id"`
	Target LadderLevel `json:"target"`
	Year   int32       `json:"year"`
}

func (q *Queries) ListLevelTargets(ctx context.Context) ([]ListLevelTargetsRow, error) {
	rows, err := q.db.Query(ctx, listLevelTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLevelTargetsRow
	for rows.Next() {
		var i ListLevelTargetsRow
		if err := rows.Scan(&i.ID, &i.Target, &i.Year); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLevelTarget = `-- name: UpdateLevelTarget :one
UPDATE level_target
SET target = $2, year = $3
WHERE id = $1
RETURNING id, year, target
`

type UpdateLevelTargetParams struct {
	ID     uuid.UUID   `json:"id"`
	Target LadderLevel `json:"target"`
	Year   int32       `json:"year"`
}

func (q *Queries) UpdateLevelTarget(ctx context.Context, arg UpdateLevelTargetParams) (LevelTarget, error) {
	row := q.db.QueryRow(ctx, updateLevelTarget, arg.ID, arg.Target, arg.Year)
	var i LevelTarget
	err := row.Scan(&i.ID, &i.Year, &i.Target)
	return i, err
}
