// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUserPlans = `-- name: CountUserPlans :one
SELECT COUNT(*) FROM plans WHERE user_id = $1
`

func (q *Queries) CountUserPlans(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserPlans, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (
    user_id, title, description, initiative_id, level_target, status
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, title, description, initiative_id, level_target, status, position, created_at, updated_at
`

type CreatePlanParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	Title        string      `json:"title"`
	Description  pgtype.Text `json:"description"`
	InitiativeID pgtype.UUID `json:"initiative_id"`
	LevelTarget  pgtype.Text `json:"level_target"`
	Status       string      `json:"status"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.InitiativeID,
		arg.LevelTarget,
		arg.Status,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.InitiativeID,
		&i.LevelTarget,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans
WHERE id = $1 AND user_id = $2
`

type DeletePlanParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePlan(ctx context.Context, arg DeletePlanParams) error {
	_, err := q.db.Exec(ctx, deletePlan, arg.ID, arg.UserID)
	return err
}

const findPlanByID = `-- name: FindPlanByID :one
SELECT id, user_id, title, description, initiative_id, level_target, status, position, created_at, updated_at FROM plans
WHERE id = $1 AND user_id = $2
`

type FindPlanByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) FindPlanByID(ctx context.Context, arg FindPlanByIDParams) (Plan, error) {
	row := q.db.QueryRow(ctx, findPlanByID, arg.ID, arg.UserID)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.InitiativeID,
		&i.LevelTarget,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPlanByTitle = `-- name: FindPlanByTitle :one
SELECT id, user_id, title, description, initiative_id, level_target, status, position, created_at, updated_at FROM plans
WHERE user_id = $1 AND LOWER(title) = LOWER($2)
LIMIT 1
`

type FindPlanByTitleParams struct {
	UserID uuid.UUID `json:"user_id"`
	Title  string    `json:"title"`
}

func (q *Queries) FindPlanByTitle(ctx context.Context, arg FindPlanByTitleParams) (Plan, error) {
	row := q.db.QueryRow(ctx, findPlanByTitle, arg.UserID, arg.Title)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.InitiativeID,
		&i.LevelTarget,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserPlans = `-- name: ListUserPlans :many
SELECT
    p.id,
    p.user_id,
    p.title,
    p.description,
    p.initiative_id,
    p.level_target,
    p.status,
    p.position,
    p.created_at,
    p.updated_at,
    i.title as initiative_title
FROM plans p
LEFT JOIN initiatives i ON p.initiative_id = i.id
WHERE p.user_id = $1
ORDER BY p.position ASC, p.created_at DESC
`

type ListUserPlansRow struct {
	ID              uuid.UUID   `json:"id"`
	UserID          uuid.UUID   `json:"user_id"`
	Title           string      `json:"title"`
	Description     pgtype.Text `json:"description"`
	InitiativeID    pgtype.UUID `json:"initiative_id"`
	LevelTarget     pgtype.Text `json:"level_target"`
	Status          string      `json:"status"`
	Position        int32       `json:"position"`
	CreatedAt       pgtype.Date `json:"created_at"`
	UpdatedAt       pgtype.Date `json:"updated_at"`
	InitiativeTitle pgtype.Text `json:"initiative_title"`
}

func (q *Queries) ListUserPlans(ctx context.Context, userID uuid.UUID) ([]ListUserPlansRow, error) {
	rows, err := q.db.Query(ctx, listUserPlans, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserPlansRow
	for rows.Next() {
		var i ListUserPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.InitiativeID,
			&i.LevelTarget,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InitiativeTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans
SET
    title = $2,
    description = $3,
    initiative_id = $4,
    level_target = $5,
    status = $6,
    updated_at = NOW()
WHERE id = $1 AND user_id = $7
RETURNING id, user_id, title, description, initiative_id, level_target, status, position, created_at, updated_at
`

type UpdatePlanParams struct {
	ID           uuid.UUID   `json:"id"`
	Title        string      `json:"title"`
	Description  pgtype.Text `json:"description"`
	InitiativeID pgtype.UUID `json:"initiative_id"`
	LevelTarget  pgtype.Text `json:"level_target"`
	Status       string      `json:"status"`
	UserID       uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.InitiativeID,
		arg.LevelTarget,
		arg.Status,
		arg.UserID,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.InitiativeID,
		&i.LevelTarget,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reorderPlan = `-- name: ReorderPlan :exec
UPDATE plans
SET position = $3, updated_at = NOW()
WHERE id = $1 AND user_id = $2
`

type ReorderPlanParams struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	Position int32     `json:"position"`
}

func (q *Queries) ReorderPlan(ctx context.Context, arg ReorderPlanParams) error {
	_, err := q.db.Exec(ctx, reorderPlan, arg.ID, arg.UserID, arg.Position)
	return err
}

const findPlanByPosition = `-- name: FindPlanByPosition :one
SELECT id, user_id, title, description, initiative_id, level_target, status, position, created_at, updated_at FROM plans
WHERE user_id = $1 AND position = $2
`

type FindPlanByPositionParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Position int32     `json:"position"`
}

func (q *Queries) FindPlanByPosition(ctx context.Context, arg FindPlanByPositionParams) (Plan, error) {
	row := q.db.QueryRow(ctx, findPlanByPosition, arg.UserID, arg.Position)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.InitiativeID,
		&i.LevelTarget,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}