// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddEvidence(ctx context.Context, arg AddEvidenceParams) (ActivityEvidence, error)
	CountAllUsers(ctx context.Context) (int64, error)
	CountUserActivities(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error)
	CreateActivityPillar(ctx context.Context, arg CreateActivityPillarParams) (ActivityPillar, error)
	CreateLadderLevel(ctx context.Context, arg CreateLadderLevelParams) (CareerLadder, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteActivity(ctx context.Context, arg DeleteActivityParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	FindActivityByID(ctx context.Context, arg FindActivityByIDParams) (FindActivityByIDRow, error)
	FindActivityComposition(ctx context.Context, userID uuid.UUID) ([]FindActivityCompositionRow, error)
	FindActivityDetail(ctx context.Context, arg FindActivityDetailParams) (FindActivityDetailRow, error)
	FindActivityWithLadder(ctx context.Context, arg FindActivityWithLadderParams) (FindActivityWithLadderRow, error)
	FindAllUsers(ctx context.Context) ([]FindAllUsersRow, error)
	FindAllUsersPaginated(ctx context.Context, arg FindAllUsersPaginatedParams) ([]FindAllUsersPaginatedRow, error)
	FindCurrentCycle(ctx context.Context) (EvaluationCycle, error)
	FindCurrentTargetLevel(ctx context.Context, year int32) (FindCurrentTargetLevelRow, error)
	FindDetailedActivityReport(ctx context.Context, userID uuid.UUID) ([]FindDetailedActivityReportRow, error)
	FindEvidencesByActivity(ctx context.Context, activityID uuid.UUID) ([]ActivityEvidence, error)
	FindGapAnalysis(ctx context.Context, arg FindGapAnalysisParams) ([]FindGapAnalysisRow, error)
	FindLadderByLevel(ctx context.Context, level LadderLevel) (CareerLadder, error)
	FindLadderLevel(ctx context.Context, id uuid.UUID) (CareerLadder, error)
	FindPdiDashboard(ctx context.Context, userID uuid.UUID) ([]FindPdiDashboardRow, error)
	FindPerformanceByPeriod(ctx context.Context, arg FindPerformanceByPeriodParams) ([]FindPerformanceByPeriodRow, error)
	FindPreviousCycle(ctx context.Context, endDate pgtype.Date) (EvaluationCycle, error)
	FindUserActivities(ctx context.Context, userID uuid.UUID) ([]FindUserActivitiesRow, error)
	FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error)
	FindUserByID(ctx context.Context, id uuid.UUID) (FindUserByIDRow, error)
	ListEntireLadder(ctx context.Context) ([]CareerLadder, error)
	ListUserActivities(ctx context.Context, userID uuid.UUID) ([]ListUserActivitiesRow, error)
	ListUserActivitiesPaginated(ctx context.Context, arg ListUserActivitiesPaginatedParams) ([]ListUserActivitiesPaginatedRow, error)
	ListUserActivitiesWithEvidences(ctx context.Context, userID uuid.UUID) ([]ListUserActivitiesWithEvidencesRow, error)
	ListUserActivitiesWithEvidencesPaginated(ctx context.Context, arg ListUserActivitiesWithEvidencesPaginatedParams) ([]ListUserActivitiesWithEvidencesPaginatedRow, error)
	UpdateActivityProgress(ctx context.Context, arg UpdateActivityProgressParams) (Activity, error)
	UpdateLadderXP(ctx context.Context, arg UpdateLadderXPParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
