// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_evidences.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTaskEvidence = `-- name: CreateTaskEvidence :one
INSERT INTO task_evidences (task_id, evidence_url, description)
VALUES ($1, $2, $3)
RETURNING id, task_id, evidence_url, description, created_at
`

type CreateTaskEvidenceParams struct {
	TaskID      uuid.UUID   `json:"task_id"`
	EvidenceUrl string      `json:"evidence_url"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateTaskEvidence(ctx context.Context, arg CreateTaskEvidenceParams) (TaskEvidence, error) {
	row := q.db.QueryRow(ctx, createTaskEvidence, arg.TaskID, arg.EvidenceUrl, arg.Description)
	var i TaskEvidence
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.EvidenceUrl,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTaskEvidence = `-- name: DeleteTaskEvidence :exec
DELETE FROM task_evidences WHERE id = $1
`

func (q *Queries) DeleteTaskEvidence(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskEvidence, id)
	return err
}

const listEvidencesByTask = `-- name: ListEvidencesByTask :many
SELECT id, task_id, evidence_url, description, created_at
FROM task_evidences
WHERE task_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListEvidencesByTask(ctx context.Context, taskID uuid.UUID) ([]TaskEvidence, error) {
	rows, err := q.db.Query(ctx, listEvidencesByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskEvidence
	for rows.Next() {
		var i TaskEvidence
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.EvidenceUrl,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
