// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_pillars.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createTaskPillar = `-- name: CreateTaskPillar :one
INSERT INTO task_pillars (task_id, pillar)
VALUES ($1, $2)
RETURNING task_id, pillar
`

type CreateTaskPillarParams struct {
	TaskID uuid.UUID `json:"task_id"`
	Pillar Pillar    `json:"pillar"`
}

func (q *Queries) CreateTaskPillar(ctx context.Context, arg CreateTaskPillarParams) (TaskPillar, error) {
	row := q.db.QueryRow(ctx, createTaskPillar, arg.TaskID, arg.Pillar)
	var i TaskPillar
	err := row.Scan(&i.TaskID, &i.Pillar)
	return i, err
}

const deleteTaskPillars = `-- name: DeleteTaskPillars :exec
DELETE FROM task_pillars WHERE task_id = $1
`

func (q *Queries) DeleteTaskPillars(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskPillars, taskID)
	return err
}

const getTaskPillars = `-- name: GetTaskPillars :many
SELECT pillar FROM task_pillars WHERE task_id = $1
`

func (q *Queries) GetTaskPillars(ctx context.Context, taskID uuid.UUID) ([]Pillar, error) {
	rows, err := q.db.Query(ctx, getTaskPillars, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pillar
	for rows.Next() {
		var pillar Pillar
		if err := rows.Scan(&pillar); err != nil {
			return nil, err
		}
		items = append(items, pillar)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
