// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const calculateInitiativeProgress = `-- name: CalculateInitiativeProgress :one
SELECT COALESCE(AVG(progress_percentage), 0)::int as avg_progress
FROM tasks
WHERE initiative_id = $1
`

func (q *Queries) CalculateInitiativeProgress(ctx context.Context, initiativeID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, calculateInitiativeProgress, initiativeID)
	var avg_progress int32
	err := row.Scan(&avg_progress)
	return avg_progress, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    initiative_id, title, execution, progress_percentage
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, initiative_id, title, execution, progress_percentage, completed_at, created_at, updated_at
`

type CreateTaskParams struct {
	InitiativeID       uuid.UUID   `json:"initiative_id"`
	Title              string      `json:"title"`
	Execution          pgtype.Text `json:"execution"`
	ProgressPercentage int32       `json:"progress_percentage"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.InitiativeID,
		arg.Title,
		arg.Execution,
		arg.ProgressPercentage,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.InitiativeID,
		&i.Title,
		&i.Execution,
		&i.ProgressPercentage,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const findTaskByID = `-- name: FindTaskByID :one
SELECT id, initiative_id, title, execution, progress_percentage, completed_at, created_at, updated_at
FROM tasks
WHERE id = $1
`

func (q *Queries) FindTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, findTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.InitiativeID,
		&i.Title,
		&i.Execution,
		&i.ProgressPercentage,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasksByInitiative = `-- name: ListTasksByInitiative :many
SELECT id, initiative_id, title, execution, progress_percentage, completed_at, created_at, updated_at,
    (SELECT COUNT(*) FROM task_evidences WHERE task_id = tasks.id)::int as evidence_count
FROM tasks
WHERE initiative_id = $1
ORDER BY created_at DESC
`

type ListTasksByInitiativeRow struct {
	ID                 uuid.UUID   `json:"id"`
	InitiativeID       uuid.UUID   `json:"initiative_id"`
	Title              string      `json:"title"`
	Execution          pgtype.Text `json:"execution"`
	ProgressPercentage int32       `json:"progress_percentage"`
	CompletedAt        pgtype.Date `json:"completed_at"`
	CreatedAt          pgtype.Date `json:"created_at"`
	UpdatedAt          pgtype.Date `json:"updated_at"`
	EvidenceCount      int32       `json:"evidence_count"`
}

func (q *Queries) ListTasksByInitiative(ctx context.Context, initiativeID uuid.UUID) ([]ListTasksByInitiativeRow, error) {
	rows, err := q.db.Query(ctx, listTasksByInitiative, initiativeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksByInitiativeRow
	for rows.Next() {
		var i ListTasksByInitiativeRow
		if err := rows.Scan(
			&i.ID,
			&i.InitiativeID,
			&i.Title,
			&i.Execution,
			&i.ProgressPercentage,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EvidenceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
    title = $2,
    execution = $3,
    progress_percentage = $4,
    completed_at = CASE WHEN $4 = 100 THEN CURRENT_DATE ELSE NULL END,
    updated_at = CURRENT_DATE
WHERE id = $1
RETURNING id, initiative_id, title, execution, progress_percentage, completed_at, created_at, updated_at
`

type UpdateTaskParams struct {
	ID                 uuid.UUID   `json:"id"`
	Title              string      `json:"title"`
	Execution          pgtype.Text `json:"execution"`
	ProgressPercentage int32       `json:"progress_percentage"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Execution,
		arg.ProgressPercentage,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.InitiativeID,
		&i.Title,
		&i.Execution,
		&i.ProgressPercentage,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
