// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAllUsers = `-- name: CountAllUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountAllUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    username, email, password, active, current_level
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	Password     string      `json:"password"`
	Active       bool        `json:"active"`
	CurrentLevel LadderLevel `json:"current_level"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Active,
		arg.CurrentLevel,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const findAllUsers = `-- name: FindAllUsers :many
SELECT id, username, email, active, current_level FROM users
`

type FindAllUsersRow struct {
	ID           uuid.UUID   `json:"id"`
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	Active       bool        `json:"active"`
	CurrentLevel LadderLevel `json:"current_level"`
}

func (q *Queries) FindAllUsers(ctx context.Context) ([]FindAllUsersRow, error) {
	rows, err := q.db.Query(ctx, findAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAllUsersRow
	for rows.Next() {
		var i FindAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Active,
			&i.CurrentLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllUsersPaginated = `-- name: FindAllUsersPaginated :many
SELECT id, username, email, active, role, current_level, created_at 
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type FindAllUsersPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type FindAllUsersPaginatedRow struct {
	ID           uuid.UUID   `json:"id"`
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	Active       bool        `json:"active"`
	Role         UserRole    `json:"role"`
	CurrentLevel LadderLevel `json:"current_level"`
	CreatedAt    pgtype.Date `json:"created_at"`
}

func (q *Queries) FindAllUsersPaginated(ctx context.Context, arg FindAllUsersPaginatedParams) ([]FindAllUsersPaginatedRow, error) {
	rows, err := q.db.Query(ctx, findAllUsersPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAllUsersPaginatedRow
	for rows.Next() {
		var i FindAllUsersPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Active,
			&i.Role,
			&i.CurrentLevel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, username, email, password, active, role, current_level FROM users WHERE email = $1
`

type FindUserByEmailRow struct {
	ID           uuid.UUID   `json:"id"`
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	Password     string      `json:"password"`
	Active       bool        `json:"active"`
	Role         UserRole    `json:"role"`
	CurrentLevel LadderLevel `json:"current_level"`
}

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i FindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Active,
		&i.Role,
		&i.CurrentLevel,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, username, email, password, active, current_level, manager_name, manager_email FROM users WHERE id = $1
`

type FindUserByIDRow struct {
	ID           uuid.UUID   `json:"id"`
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	Password     string      `json:"password"`
	Active       bool        `json:"active"`
	CurrentLevel LadderLevel `json:"current_level"`
	ManagerName  pgtype.Text `json:"manager_name"`
	ManagerEmail pgtype.Text `json:"manager_email"`
}

func (q *Queries) FindUserByID(ctx context.Context, id uuid.UUID) (FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Active,
		&i.CurrentLevel,
		&i.ManagerName,
		&i.ManagerEmail,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET
    username = $2,
    email = $3,
    password = $4,
    active = $5,
    current_level = $6,
    manager_name = $7,
    manager_email = $8
WHERE id = $1
`

type UpdateUserParams struct {
	ID           uuid.UUID   `json:"id"`
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	Password     string      `json:"password"`
	Active       bool        `json:"active"`
	CurrentLevel LadderLevel `json:"current_level"`
	ManagerName  pgtype.Text `json:"manager_name"`
	ManagerEmail pgtype.Text `json:"manager_email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Active,
		arg.CurrentLevel,
		arg.ManagerName,
		arg.ManagerEmail,
	)
	return err
}
